#ifndef QEVERCLOUD_GENERATOR_THRIFT_PARSER_GENERATOR_H
#define QEVERCLOUD_GENERATOR_THRIFT_PARSER_GENERATOR_H

#include "Parser.h"

void generateSources(Parser * parser, QString outPath);

#endif // QEVERCLOUD_GENERATOR_THRIFT_PARSER_GENERATOR_H
